# config/_default/menus.toml

[[main]]
  name = "投稿一覧"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "カテゴリー"
  pageRef = "categories"
  weight = 20

[[main]]
  name = "出典"
  pageRef = "sources"
  weight = 30

[[main]]
  name = "タグ"
  pageRef = "tags"
  weight = 40

[[main]]
  name = "当サイトについて"
  pageRef = "about"
  weight = 90

# [[main]]
#   pre = "github"
#   name = "GitHub"
#   url = "https://github.com/nunocoracao/blowfish"
#   weight = 30

# [[main]]
#   identifier = "github2"
#   pre = "github"
#   url = "https://github.com/nunocoracao/blowfish"
#   weight = 40

# [[footer]]
#   name = "Privacy"
#   url = "https://external-link"


